### ISSUE TITLE
Animar sprites genéricos

### ISSUE THREAD

**Issue by ariane2980** [ifscgf/Gravity-Falls#10]
No jogo em desenvolvimento, definir em código a movimentação dos personagens e animação dos sprites (ou spritesheets) no cenário do jogo. Depende de #9.

Se o jogo for apenas de texto, entende-se aqui pelo texto que tem alteração de forma ou conteúdo durante a leitura (pistas etc.).

**Comment by AyrtonSilva26** [comment]
Aniamção do personagem - cliente/cena7.js - linha 37 em diante
