### ISSUE TITLE
Reagir a colisão entre personagem(ns) e objetos do cenário

### ISSUE THREAD

**Issue by ariane2980** [ifscgf/Gravity-Falls#13]
Em #12, há a detecção de colisões entre personagem(ns) e objetos do cenário. Aqui, deve haver um desdobramento desses eventos, como perder energia, adicionar um objeto ao inventário etc. Dependente, obviamente, de #12.

Nos jogos baseados em texto, esta tarefa se refere às ações disparadas quando um link ou área clicável é acionada.

**Comment by AyrtonSilva26** [comment]
Coleta de itens o faz desaparecer e toca um som.
