### ISSUE TITLE
Definir uma cena maior que a tela

### ISSUE THREAD

**Issue by ariane2980** [ifscgf/Gravity-Falls#14]
Deve-se ter uma cena maior que a tela, para que assim o jogo defina a forma de apresentar o jogo para o jogador com o (futuro) uso de câmera para apresentar o jogo.

Nos jogos baseados em texto, é quando o texto se estende além da tela, devendo haver, portanto, rolagem vertical ou horizontal do texto para sua leitura completa.

**Comment by AyrtonSilva26** [comment]
Isso não será feito no jogo pois contará apenas mapa estático, um jogador verá o mapa todo e outro terá uma visão limitada do mapa a partir de zoom e efeito vinheta
