### ISSUE TITLE
Definir câmera para seguir personagem em foco

### ISSUE THREAD

**Issue by ariane2980** [ifscgf/Gravity-Falls#15]
Esta tarefa depende de #14, pois com a cena maior que a tela é hora de definir e programar uma câmera para seguir o personagem em foco se deslocando pela cena.

Nos jogos baseados em texto, esta tarefa é opcional: quando o posicionamento da leitura não acompanha o texto, na intenção de gerar alguma reação compatível com o jogo (texto escondido, easter egg etc.).

**Comment by AyrtonSilva26** [comment]
definido em "cliente/cena1.js - linhas 479 à 483"
