### ISSUE TITLE
Definir 2 ou mais cenas

### ISSUE THREAD

**Issue by ariane2980** [ifscgf/Gravity-Falls#16]
Para as cenas de abertura de abertura e de encerramento de jogo, é recomendado dividir o jogo em cenas. Aqui, o objetivo é apenas dividir conceitualmente o jogo em várias cenas. Logo, esta tarefa depende de #13, e recomendado fazê-la depois #15.

Nos jogos baseados em texto, é a criação de 2 ou mais páginas/seções/capítulos, onde esses são independentes entre si. No Twine, por exemplo, são as passagens do texto.

**Comment by AyrtonSilva26** [comment]
dentro da pasta "cliente" está definida 3 cenas que serão utilizadas a priori, são estas: 
"cena0.js" --> Tela de abertura;
"cena1.js" --> Gameplay;
"cena2.js" --> Tela de encerramento.
