### ISSUE TITLE
Definir e projetar tela de abertura

### ISSUE THREAD

**Issue by ariane2980** [ifscgf/Gravity-Falls#17]
Para que o jogo funcione plenamente, incluindo áudio, é interessante adicionar uma tela de abertura para que o jogador possa interagir e carregar, ao fundo, os arquivos do jogo. Esta tarefa contempla essas duas subtarefas:

- [ ] Definir a tela de abertura;
- [ ] Programar a tela de abertura.

Depende de #16.

Nos jogos baseados em texto, é a escrita e formação das páginas/seções/capítulos iniciais e finais - pelo menos sua estrutura básica (cores, título etc.).

**Comment by AyrtonSilva26** [comment]
código em "cliente/cena0.js", arquivos em: "cliente/assets/cena0.png", "cliente/assets/play.png", "cliente/assets/openning.mp3"
