### ISSUE TITLE
Definir e projetar tela de encerramento

### ISSUE THREAD

**Issue by ariane2980** [ifscgf/Gravity-Falls#18]
Assim como a tela de abertura #17, a tela de encerramento ajudará, durante o jogo, a (re)carregar os objetos das cenas, zerar placar, entre outros. São, pois, também duas subtarefas:

 Definir a tela de encerramento;
 Programar a tela de encerramento.
Depende de #16, e recomenda-se fazer depois de #17.

Nos jogos baseados em texto, É um rascunho do(s) (provável(is)) fim(ns) do jogo.

**Comment by AyrtonSilva26** [comment]
Tela de encerramento em: "cliente/cena2.js", arquivos em: "cliente/assets/final.png" e "cliente/assets/voltar.png"
