### ISSUE TITLE
Adicionar suporte a tela cheia

### ISSUE THREAD

**Issue by ariane2980** [ifscgf/Gravity-Falls#21]
Adicionar um botão ou tecla de atalho para ativar ou desativar a tela cheia para o jogo. Recomenda-se fazer depois de #16. Recomendada a mesma solução usada em [boiadacarapreta/phaser3#1](https://github.com/boidacarapreta/phaser3/issues/1).

**Comment by AyrtonSilva26** [comment]
Tarefa feita, linhas 180 a 215 - cliente/cena1.js.
