### ISSUE TITLE
Criar placar local em memória não persistente

### ISSUE THREAD

**Issue by ariane2980** [ifscgf/Gravity-Falls#22]
Por enquanto, criar um placar na tela para persistir enquanto o jogador estiver com o jogo carregado em memória, não necessitando armazenar essas informações em sistema externo como banco de dados. Recomenda-se fazer depois de #16.

**Comment by AyrtonSilva26** [comment]
linhas: 481 a 485, 541 a 550, 666 a 675, 701 a 705 - cliente/cena1.js
