### ISSUE TITLE
Adicionar segundo personagem em cena

### ISSUE THREAD

**Issue by ariane2980** [ifscgf/Gravity-Falls#23]
Utilizando apenas um conjunto de entrada teclado+mouse e uma saída, o monitor, adicionar o suporte a pelo menos dois jogadores. Provavelmente dependerá de #22, e recomenda-se fazer depois de #16. Como subtarefas:

 

- [ ] Definir arte do segundo personagem;
- [ ] Posicionar ambos os personagens em tela.

**Comment by AyrtonSilva26** [comment]
Personagem 2 genérico incluído no jogo.
