### ISSUE TITLE
Programar interação entre segundo personagem e jogo

### ISSUE THREAD

**Issue by ariane2980** [ifscgf/Gravity-Falls#24]
Na continuação de #23, esta tarefa se refere a interação com o jogo:

 

- [ ] Definir como a câmera se comportará com os dois;
- [ ]  Programar a interação dos objetos da cena com ambos os personagens;
- [ ]  Jogo (e placar) colaborativo? Cooperativo? Competitivo?

**Comment by AyrtonSilva26** [comment]
O personagem 2 pode coletar item e colide com os objetos.
