### ISSUE TITLE
Publicar a versão v0.1 do jogo no GitHub Pages

### ISSUE THREAD

**Issue by ariane2980** [ifscgf/Gravity-Falls#25]
Publicar o jogo em sua primeira versão experimental, `v0.1`, no GitHub Pages.

**Comment by AyrtonSilva26** [comment]
Publicado.

**Comment by ghost** [comment]
Vocês já podem mover os arquivos do cliente da pasta `cliente` para a raiz - e atualizar no código do servidor HTTP.
