### ISSUE TITLE
Estudar DNS

### ISSUE THREAD

**Issue by ariane2980** [ifscgf/Gravity-Falls#28]
Publicado no canal da disciplina o [vídeo](https://www.youtube.com/watch?v=KBjd8FD-P4Y) com resumo do conteúdo de terceiros sobre os conceitos básicos do DNS:

- [Como funciona a Internet?](https://www.youtube.com/watch?v=ACGuo26MswI)
- [A Importância do DNS nas redes, explicada pelo NIC.br](https://www.youtube.com/watch?v=epWv0-eqRMw)
- [Nivelamento de protocolo DNS e configuração de DNS reverso](https://www.youtube.com/watch?v=cRneZs9Lvno) (OPCIONAL)
- [O que é DNS?](https://www.cloudflare.com/pt-br/learning/dns/what-is-dns/)
- [Servidores raiz do DNS](https://root-servers.org/)

**Comment by boidacarapreta** [comment]
Registro `CNAME` criado:

```sh
$ dig A gravityfallsgame.ifsc.cloud

; <<>> DiG 9.10.3-P4-Debian <<>> A gravityfallsgame.ifsc.cloud
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 62701
;; flags: qr rd ra; QUERY: 1, ANSWER: 5, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1232
;; QUESTION SECTION:
;gravityfallsgame.ifsc.cloud.	IN	A

;; ANSWER SECTION:
gravityfallsgame.ifsc.cloud. 1799 IN	CNAME	ifscgf.github.io.
ifscgf.github.io.	3600	IN	A	185.199.110.153
ifscgf.github.io.	3600	IN	A	185.199.111.153
ifscgf.github.io.	3600	IN	A	185.199.108.153
ifscgf.github.io.	3600	IN	A	185.199.109.153

;; Query time: 961 msec
;; SERVER: 191.36.8.66#53(191.36.8.66)
;; WHEN: Mon May 23 07:46:36 -03 2022
;; MSG SIZE  rcvd: 150
```
