### ISSUE TITLE
Definir hospedagem do servidor do jogo

### ISSUE THREAD

**Issue by ariane2980** [ifscgf/Gravity-Falls#30]
Definir forma e local de hospedagem do servidor de jogo para que os clientes possam de conectar:

- GCP?
- AWS?
- Azure?
- Heroku?
- (Outro)?

Impactado por #29.

**Comment by AyrtonSilva26** [comment]
URL: gravityfallsgame.ifsc.cloud - Servidor: gf.ifsc.cloud

**Comment by ariane2980** [comment]
Estático = Github Pages.
Dinâmico = Heroku.
