### ISSUE TITLE
Definir protocolo entre servidor e clientes

### ISSUE THREAD

**Issue by ariane2980** [ifscgf/Gravity-Falls#31]
Definir as mensagens (formato, cabeçalho, corpo) entre servidor e clientes/jogadores para a opção de multijogador local com placar. Depende de #27 e #33. Recomendado os mecanismos do [Socket.IO](https://socket.io/) para estabelecimento (`connection`) e encerramento (`disconnect`) de conexão.

**Comment by AyrtonSilva26** [comment]
No método `create()`:

```js
socket.on("desenharOutroJogador", ({ frame, x, y }) => {
    if (jogador === 1) {
      player2.setFrame(frame);
      player2.x = x + 8;
      player2.y = y + 7.5;
    } else if (jogador === 2) {
      player1.setFrame(frame);
      player1.x = x + 8;
      player1.y = y + 8;
    }
  });
};
```

No método `update()`:

```js
socket.emit("estadoDoJogador", {
      frame: player1.anims.getFrameName(),
      x: player1.body.x,
      y: player1.body.y,
    });
```
