### ISSUE TITLE
Integrar servidor de jogo e clientes

### ISSUE THREAD

**Issue by ariane2980** [ifscgf/Gravity-Falls#35]
Modificar os clientes de #25 e o servidor de #32 e #34 e integrá-los, de forma a ter um jogo multijogador em rede.

**Comment by AyrtonSilva26** [comment]
Código do cliente em #31.
Código do servidor: 

```js
socket.on("estadoDoJogador", function (estado) {
    socket.broadcast.emit("desenharOutroJogador", estado);
  });
```
