### ISSUE TITLE
Definir salas de partida

### ISSUE THREAD

**Issue by ariane2980** [ifscgf/Gravity-Falls#37]
Usar namespaces ou outro mecanismo para criar salas de partida entre vários jogadores. Sugestão de tutorial: Build An Among Us Inspired Live-Multiplayer Game with Phaser 3 and Socket.io partes [1](https://hannahrobot.com/2020/12/04/build-among-us-live-multiplayer-phaser-3-socket/), [2](https://hannahrobot.com/2020/12/06/build-among-us-live-multiplayer-phaser-3-socket-part-2/) e [3](https://hannahrobot.com/2020/12/15/build-among-us-live-multiplayer-phaser-3-socket-part-3/). Depende de #32 e #34.

**Comment by AyrtonSilva26** [comment]
commit 3f9b8f2cff61881681cf06974e3134e0ac30463f
