### ISSUE TITLE
Usar imagem genérica de fundo

### ISSUE THREAD

**Issue by ariane2980** [ifscgf/Gravity-Falls#8]
Usar uma imagem da Internet, sem restrição de direitos autorais, para usar no desenvolvimento do jogo. Não precisa, logo, ser a imagem final do jogo, mas apenas uma mais genérica para auxiliar no processo.

Se o jogo não tiver imagem, mas apenas texto, basta a cor, portanto.

**Comment by AyrtonSilva26** [comment]
cliente/cena7.js - código que coloca o cenário no jogo, cliente/assets/ground.png - imagem de fundo

**Comment by AyrtonSilva26** [comment]
cliente/cena7.js - código que coloca o cenário no jogo, cliente/assets/ground.png - imagem de fundo
