### ISSUE TITLE
Usar sprites genéricos de animação

### ISSUE THREAD

**Issue by ariane2980** [ifscgf/Gravity-Falls#9]
Assim como a imagem genérica de fundo #8, utilizar sprites prontos da Internet, sempre sem restrição de direito autoral, para usar durante o desenvolvimento do jogo. Assim como a imagem, se o jogo for apenas de texto, trocar esta tarefa pelas fontes a serem usadas.

**Comment by AyrtonSilva26** [comment]
animação - cliente/assets/billcipher.png - código da animação: cliente/cena7.js
